### ISSUE TITLE
Crash When i changed interior/exterior and the server didn't start anymore

### ISSUE THREAD

**Issue by Baffero** [CommandrMoose/TardisRefined#207]
### Issue description

I installed the mod and growth a tardis, all well when i terraformed it, can exit and enter, first i changed the exterior but i cant go out from the tardis, i canged the interior too and i cant go out too, so i did /home and server crashed. Now i cannot start the server always crash with this crash-log. i hope i can fix this i'm really fan of the series and i want to play the mod. i'm using the version 1.19.2, 1.0.1 with forge 43.3.7

### Steps to reproduce

1. tardis growth,
2. terraforming
3. enter/exit
4. change exterior (cant exit from door)
5. changed interior (no visual changes) and tried to exit once more.
6. did /home to go to overworld
7. server crashed and cant start it again, 

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

43.3.7

### Tardis Refined version

v1.0

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://pastebin.com/fhXxe9ds , https://pastebin.com/QKTQm5XK

**Comment by CommandrMoose** [comment]
This is a known issue that's in the current release versions. 

What's happening here is that the time it takes to generate the interior content, such as the first interior or cave is less than optimal and cause a ticks to halt. The server watchdog you're using (since you've got /home I assume it's something like Spigot) has a "if we're frozen for a certain amount of time, kill the server and restart". The mod doesn't expect this so when you relog it expects a TARDIS shell to be present somewhere that it's not. 

This is fixed in the upcoming update, but for now I recommend trying contact your server host to resolve the issue with your server.  Alternatively, try launching the server without the mod then add it back to reload.

**Comment by Baffero** [comment]
Thanks, i'll try that

**Comment by Baffero** [comment]
temporaly fixed removing the mod and re enabling the mod. i can enter the tardis but cant go out from the inside, tried to change exterior model and did /home to return to overworld and all the models of the tardis appear really bugged. The server only crashes when i try to change the interior of the tardis. I tried to disconect from the server after changing to nuke in the terminal and instantly crashed. i have full access to the server in a ubuntu server VM if it helps that i can change things to try to fix it

**Comment by Baffero** [comment]
I've fixed the simplest way possible, all i had to do is move the tardis, now i can enter and exit without problems and change the console in terminal and all was perfect, i really like this mod great job!!!!

**Comment by Baffero** [comment]
I've fixed the simplest way possible, all i had to do is move the tardis, now i can enter and exit without problems and change the console in terminal and all was perfect, i really like this mod great job!!!!
