### ISSUE TITLE
Dimension Switch midflight

### ISSUE THREAD

**Issue by KiloTheNeko** [CommandrMoose/TardisRefined#269]
### Issue description

when the dimension selector gets misaligned and you press it to fix it it will genuinely get misaligned by selecting a different dimensions from the one you wanted.

### Steps to reproduce

1. start a longer flight
2. wait for the dimension selector to break
3. quickly press it 
4. be unable to switch it back

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

FL 0.15.4-1.20.2

### Tardis Refined version

v2.0

**Comment by Jeryn99** [comment]
Hey I wanna understand this properly, would you say these are the steps?

- Go into Flight
- Dimension control gets misaligned but not dead
- Undoing the misalignment causes a dimension change that you can't get out of?

**Comment by 50ap5ud5** [comment]
This was caused by two problems, both of which have been resolved for the next release:
1. ControlEntity allowing players to activate the Control's function during a flight dance alignment events. (i.e. Using the dimension control when trying to re-align the "broken" control would switch dimension)
2. Control(s) that were meant to be excluded from the FlightDanceManager were not actually being excluded due to erroenous filter logic.
