### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by Grain2077** [CommandrMoose/TardisRefined#326]
### Issue description

When I try to start my server with TARDIS refined, it crashes when ever someone joins.

### Minecraft version

1.20.1

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric 0.15.11

### Tardis Refined version

v2.0.3

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://pastebin.com/Me7B666n

**Comment by Jeryn99** [comment]
Looks like your server isn't connected to the internet or is banned from accessing this url? https://mc.craig.software/api/skin/beta_players

**Comment by Grain2077** [comment]
It should be connected as it's a bisect server and how would I check if it's banned?

**Comment by Jeryn99** [comment]
Depends on their server setup, I recommend getting in contact with them over a ticket and linking this class to them and explain that the server is timing out trying to validate tester players: https://github.com/WhoCraft/TardisRefined/blob/minecraft/1.20.1/common/src/main/java/whocraft/tardis_refined/ControlGroupCheckers.java


This is something I will improve on in the next version so that the beta testers code only ever runs when the game is in test mode

**Comment by Grain2077** [comment]
Could it be the website is offline as I can;t open it on my computer and the server started about an hour ago with no changes

**Comment by Noach05** [comment]
The server worked fine at first, and then stopped working suddenly

**Comment by Jeryn99** [comment]
Try now?

**Comment by Noach05** [comment]
Fixed now yeah, cheers. Dont suppose you're able to make a hotfix that makes it so if the site is offline the server can run anyway?

**Comment by Jeryn99** [comment]
100%

**Comment by Grain2077** [comment]
It's happened again

**Comment by Jeryn99** [comment]
Please download version 2.0.4

**Comment by Noach05** [comment]
Cheers, thank you very much
