### ISSUE TITLE
Data Pack/Resource Pack Issue

### ISSUE THREAD

**Issue by Captain238120** [CommandrMoose/TardisRefined#332]
### Issue description

After tons of trial and error, I believe this might just be a bug/problem (especially since I've seen a few other people ask about it).
When following the tutorial on how to make a Data Pack and Resource Pack for patterns (in my case, I'm trying to make custom shells), the tutorial either does not give enough detail or just does not work. I've gotten some help before from swirtzly before about putting tardis_refined/tardis_refined for the Data Pack, but now I am just getting either missing textures or completely black/non-existent textures.
I might be doing something/several things wrong, but after tons of changes to how I make the DP/RP and following other people's guides, I thought it would finally be time to ask the question on here.
Below I have attached both the DP and the RP:
[rbspackdp.zip](https://github.com/user-attachments/files/16117411/rbspackdp.zip)
[rbspackrp.zip](https://github.com/user-attachments/files/16117412/rbspackrp.zip)
If anyone, staff or community member, can help me out with this issue, that would be great!

### Minecraft version

1.20.1

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric Loader 0.15.10

### Tardis Refined version

v2.0.3

**Comment by Captain238120** [comment]
I also provided base mod textures in there, just to show that it probably isn't a texture issue and is instead potentially a pathing issue that I just can't figure out.

**Comment by Jeryn99** [comment]
Hello, I usually spend a little time helping people on the Discord with their packs because we want to see people using the systems, I am "swirtzly" on Discord and I assume I helped you before

When creating a pack, ensure that you are following Minecrafts guidelines in conjunction with our guides, as our guide is not comprehensive and assumes you've got a little experience with datapacks and resourcepacks

![image](https://github.com/WhoCraft/TardisRefined/assets/36424503/fa023db5-1c27-4f51-a9a7-8cdf6e0351e7)

Your pack works for me? Of course, this was after I unzipped both packs

If you are shipping your pack as a zip, you must make sure the root of the zips look like this:

Datapack:
![image](https://github.com/WhoCraft/TardisRefined/assets/36424503/3cf10dc4-60c8-4651-8cd8-aa3db22d0b4c)

Resource Pack:
![image](https://github.com/WhoCraft/TardisRefined/assets/36424503/f03d1524-fbf7-438f-811d-8188aa0cc119)


The ``rbspack`` folder is not needed within a zip

**Comment by Captain238120** [comment]
Hi, thank you for helping earlier btw! While the pack somehow works on your end, I still get this issue (I took some screenshots of both the "test" exterior and the "black" exterior):

![Screenshot (179)](https://github.com/WhoCraft/TardisRefined/assets/169954947/6f4785ed-ec12-45d4-b8d7-5e96ec0354a3)
![Screenshot (178)](https://github.com/WhoCraft/TardisRefined/assets/169954947/d2a34795-1e4d-470e-a40f-d780b03d897d)
![Screenshot (182)](https://github.com/WhoCraft/TardisRefined/assets/169954947/f392bd9f-0628-4e00-8415-1d912ff25761)
![Screenshot (181)](https://github.com/WhoCraft/TardisRefined/assets/169954947/93cc6349-e085-44f3-a6cc-931e4a79c0b4)
![Screenshot (180)](https://github.com/WhoCraft/TardisRefined/assets/169954947/08296a49-706f-4c72-af9b-b12088aa3948)

**Comment by Jeryn99** [comment]
Do you have some obscure rendering mods installed or is this just TR?

**Comment by Captain238120** [comment]
No rendering mods, no. So it would just be TR doing this. I even checked by playing the mod by itself, and I still get this same result.

**Comment by Jeryn99** [comment]
[jeryn_rbpack.zip](https://github.com/user-attachments/files/16117516/jeryn_rbpack.zip)


Try with this?

**Comment by Captain238120** [comment]
Yes, it is now working! Was there anything you changed that I should know about for future reference?

**Comment by Jeryn99** [comment]
Just what I said above
