### ISSUE TITLE
Every time I restart my server, my TARDIS disappears

### ISSUE THREAD

**Issue by Dromnil** [CommandrMoose/TardisRefined#344]
### Issue description

So twice now on my server, my TARDIS has disappeared upon restarting the server, which is unavoidable. I mentioned in the steps to reproduce what exactly happens, but I should mention that both of my TARDISes still exist, I tried teleporting to their interior dimensions, but upon going inside the airlock, my server is now eternally crashing unless I can find a way to get myself out of there. I'm more worried about needing to make a new TARDIS every time I restart the server, even just a workaround would be helpful if anyone knows of a way to prevent this. I know maybe I could try summoning it to a landing pad but that would mean I would need to put one everywhere I want it to be able to go.

I can try to get the server crash log, but I am unable to right now.

### Steps to reproduce

1: Have an active TARDIS 
2: be outside of it
3: restart the server, saving all chunks, playerdata, etc.
4: relog only to find that it's completely gone

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

Latest version of forge

### Tardis Refined version

v2.0.4

**Comment by Dromnil** [comment]
![Host machine](https://github.com/user-attachments/assets/0b205836-c65f-4711-993d-72696b4178aa)
This happens when I join the world inside the airlock after directly teleporting to the TARDIS dimension.

**Comment by Dromnil** [comment]
I have just tried to teleport into my tardis, refuel and set it's coordinates for my house, and as soon as I hit the throttle (once it was ready) it crashed the server 
[crash-2024-07-23_14.29.18-server.txt](https://github.com/user-attachments/files/16353026/crash-2024-07-23_14.29.18-server.txt)
[latest (1).log](https://github.com/user-attachments/files/16353040/latest.1.log)
I should mention that this is a very large modpack.

**Comment by Dromnil** [comment]
![image](https://github.com/user-attachments/assets/ed25ca94-5b3c-4ad3-997b-2ad6aab5a1b5)
![image](https://github.com/user-attachments/assets/94d53993-a3f7-4249-bd8a-c694f63147f3)
It seems as well that when the server crashes/restarts, all of the TARDIS data, such as upgrades and fuel level, are also wiped. I assume this may be because the server does not account for saving this data, although it does save all dimensions by default. It also set my GPS coordinates back to 0,0,0.

**Comment by Dromnil** [comment]
Lastly for now, the mod itself seems to possibly be causing some server lag, as after adding it, once the tardis is loaded in, my server keeps throwing this message, which usually stops at 100% but now repeats infinitely, even after restarting. It increases server lag and lowers TPS significantly.
![image](https://github.com/user-attachments/assets/4ee19e65-4d34-4676-bb33-ecf3da8e2f8e)
edit: after removing the mod, this has stopped happening, so it is the culprit in some way.

**Comment by Jeryn99** [comment]
> Lastly for now, the mod itself seems to possibly be causing some server lag, as after adding it, once the tardis is loaded in, my server keeps throwing this message, which usually stops at 100% but now repeats infinitely, even after restarting. It increases server lag and lowers TPS significantly. ![image](https://private-user-images.githubusercontent.com/148384642/351451233-4ee19e65-4d34-4676-bb33-ecf3da8e2f8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NjMyNDUsIm5iZiI6MTcyMTc2Mjk0NSwicGF0aCI6Ii8xNDgzODQ2NDIvMzUxNDUxMjMzLTRlZTE5ZTY1LTRkMzQtNDY3Ni1iYjMzLWVjZjNkYThlMmY4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QxOTI5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTVjYjgzMzlmN2VmMDFlODAzNDRkNjMwOGVlYWE1MzE2MmI5NWQzN2Q0NzkzOTJkM2E0NDIxMzBhOWNhZDIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GJ0ibMyX5TuCxeZ9U7AL4LJoD4qjnIseywMpLmOBH2g) edit: after removing the mod, this has stopped happening, so it is the culprit in some way.

Average Dimension lag, not something of concern





> I have just tried to teleport into my tardis, refuel and set it's coordinates for my house, and as soon as I hit the throttle (once it was ready) it crashed the server [crash-2024-07-23_14.29.18-server.txt](https://github.com/user-attachments/files/16353026/crash-2024-07-23_14.29.18-server.txt) [latest (1).log](https://github.com/user-attachments/files/16353040/latest.1.log) I should mention that this is a very large modpack.

Looks like you broke a door at some point and now the TARDIS cannot find one

**Comment by Dromnil** [comment]
> Looks like you broke a door at some point and now the TARDIS cannot find one

The interior door? I've been very careful not to, If you mean the exterior door, that's what keeps disappearing on it's own and there's nothing I can do about it.

**Comment by Dromnil** [comment]
> Average Dimension lag, not something of concern

https://github.com/user-attachments/assets/38939129-b00e-4d40-adbb-77fab78c6bbf

https://github.com/user-attachments/assets/4608efb3-75ca-49d8-8db2-2080768e990d

With the server constantly sending updates, the lag is very noticable. I added back the mod fresh without interacting with it at all and experienced this, the second video is what happened right after I removed it.

**Comment by Dromnil** [comment]
As a followup, I've done more testing on the lag issue. I deleted my old tardis data and reinstalled the mod. The issue no longer persists, but the instant that I shear a root into a functioning portal/interior/TARDIS, the console has the same message of "Preparing spawn area: 100%". I imagine the discrepency is because I have less chunks loaded in than I previously have. There may be a memory leak, and I'll add that this is also on the current neoforge version of 2.0.4

That being said, the issue of the TARDIS ceasing to exist is still in effect on this version as well.
![image](https://github.com/user-attachments/assets/f66eca4e-81f1-4843-94f7-23bbfc5ab4be)
It was right here, sorry for not taking a pre and post screenshot!

I hope this info helps you guys identify the issue. Thanks!

**Comment by ZeroDragoneer** [comment]
having the same problem but when i teleport inside though commands the dimension is just flat bedrock. have this issue since first install on 1.18.2. bug still in 1.20.1
maybe its a mod problem. like a different mod is intefiring with the tardis refined. my modpack list is too large to look into it.
or maybe because i use arclight as a server? who know. in mine log i find that tardis loading save data had a error because "this.world.K" is null. don't know what that mean.

**Comment by ZeroDragoneer** [comment]
this is the error when trying to load the save data

<html>
<body>

[Server thread/ERROR] [net.minecraft.world.level.storage.DimensionDataStorage/]: Error loading saved data: capabilities
--
12130 | java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.storage.PrimaryLevelData.m_5462_()" because "this.world.K" is null
12131 | at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.getName(CraftWorldMixin.java:602) ~[arclight-1.20.1-1.0.6-SNAPSHOT-b2cde4a.jar%23313!/:arclight-1.20.1-1.0.6-SNAPSHOT-b2cde4a] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftWorldMixin,pl:mixin:A,re:mixin}
12132 | at org.bukkit.craftbukkit.v1_20_R1.CraftServer.addWorld(CraftServerMixin.java:1255) ~[arclight-1.20.1-1.0.6-SNAPSHOT-b2cde4a.jar%23313!/:arclight-1.20.1-1.0.6-SNAPSHOT-b2cde4a] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,re:mixin}
12133 | at net.minecraft.world.level.Level.getWorld(LevelMixin.java:1228) ~[server-1.20.1-20230612.114412-srg.jar%23465!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:cloud,pl:mixin:APP:mixins.arclight.core.json:world.level.LevelMixin,pl:mixin:APP:apugli.mixins.json:common.LevelMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud}
12134 | at org.bukkit.craftbukkit.v1_20_R1.CraftChunk.getWorld(CraftChunk.java:74) ~[arclight-1.20.1-1.0.6-SNAPSHOT-b2cde4a.jar%23313!/:arclight-1.20.1-1.0.6-SNAPSHOT-b2cde4a] {re:mixin,re:classloading}
12135 | at org.bukkit.event.world.ChunkEvent.<init>(ChunkEvent.java:13) ~[arclight-1.20.1-1.0.6-SNAPSHOT-b2cde4a.jar%23313!/:arclight-1.20.1-1.0.6-SNAPSHOT-b2cde4a] {re:mixin,re:classloading}
12136 | at org.bukkit.event.world.ChunkLoadEvent.<init>(ChunkLoadEvent.java:16) ~[arclight-1.20.1-1.0.6-SNAPSHOT-b2cde4a.jar%23313!/:arclight-1.20.1-1.0.6-SNAPSHOT-b2cde4a] {re:mixin,re:classloading}
12137 | at net.minecraft.world.level.chunk.LevelChunk.loadCallback(LevelChunkMixin.java:943) ~[server-1.20.1-20230612.114412-srg.jar%23465!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.level.chunk.LevelChunkMixin,pl:mixin:APP:moonlight-common.mixins.json:LevelChunkMixin,pl:mixin:A}
12138 | at net.minecraft.world.level.chunk.LevelChunk.bridge$loadCallback(LevelChunkMixin.java:925) ~[server-1.20.1-20230612.114412-srg.jar%23465!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.level.chunk.LevelChunkMixin,pl:mixin:APP:moonlight-common.mixins.json:LevelChunkMixin,pl:mixin:A}
12139 | at io.izzel.arclight.common.mod.util.ArclightCallbackExecutor.run(ArclightCallbackExecutor.java:21) ~[arclight-1.20.1-1.0.6-SNAPSHOT-b2cde4a.jar%23313!/:arclight-1.20.1-1.0.6-SNAPSHOT-b2cde4a] {re:mixin,re:classloading}
12140 | at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache_MainThreadExecutorMixin.java:638) ~[server-1.20.1-20230612.114412-srg.jar%23465!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.level.ServerChunkCache_MainThreadExecutorMixin,pl:mixin:A}
12141 | at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23465!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
12142 | at net.minecraft.server.level.ServerChunkCache.m_7587_(ServerChunkCacheMixin.java:131) ~[server-1.20.1-20230612.114412-srg.jar%23465!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ChunkLoadDebug,pl:mixin:APP:mixins.arclight.core.json:server.level.ServerChunkCacheMixin,pl:mixin:APP:immersive_melodies.mixin.json:ServerChunkManagerMixin,pl:mixin:APP:pehkui.mixins.json:compat1201minus.compat117plus.ServerChunkManagerMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.chunk_deadlock.ServerChunkCache_CurrentLoadingMixin,pl:mixin:A}
12143 | at net.minecraft.world.level.Level.m_6522_(LevelMixin.java:187) ~[server-1.20.1-20230612.114412-srg.jar%23465!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:cloud,pl:mixin:APP:mixins.arclight.core.json:world.level.LevelMixin,pl:mixin:APP:apugli.mixins.json:common.LevelMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud}
12144 | at net.minecraft.world.level.LevelReader.m_46819_(LevelReader.java:129) ~[server-1.20.1-20230612.114412-srg.jar%23465!/:?] {re:computing_frames,re:mixin,re:classloading,re:mixin}
12145 | at net.minecraft.world.level.Level.m_6325_(LevelMixin.java:182) ~[server-1.20.1-20230612.114412-srg.jar%23465!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:cloud,pl:mixin:APP:mixins.arclight.core.json:world.level.LevelMixin,pl:mixin:APP:apugli.mixins.json:common.LevelMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud}
12146 | at net.minecraft.world.level.Level.m_46745_(LevelMixin.java:178) ~[server-1.20.1-20230612.114412-srg.jar%23465!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:cloud,pl:mixin:APP:mixins.arclight.core.json:world.level.LevelMixin,pl:mixin:APP:apugli.mixins.json:common.LevelMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud}
12147 | at net.minecraft.world.level.Level.m_7702_(LevelMixin.java:560) ~[server-1.20.1-20230612.114412-srg.jar%23465!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:cloud,pl:mixin:APP:mixins.arclight.core.json:world.level.LevelMixin,pl:mixin:APP:apugli.mixins.json:common.LevelMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud}
12148 | at whocraft.tardis_refined.common.capability.TardisLevelOperator.deserializeNBT(TardisLevelOperator.java:115) ~[tardis_refined-1.20.1-2.0.3.jar%23438!/:?] {re:classloading}
12149 | at whocraft.tardis_refined.common.capability.forge.TardisLevelOperatorImpl.deserializeNBT(TardisLevelOperatorImpl.java:80) ~[tardis_refined-1.20.1-2.0.3.jar%23438!/:?] {re:classloading}
12150 | at whocraft.tardis_refined.common.capability.forge.TardisLevelOperatorImpl.deserializeNBT(TardisLevelOperatorImpl.java:22) ~[tardis_refined-1.20.1-2.0.3.jar%23438!/:?] {re:classloading}
12151 | at net.minecraftforge.common.capabilities.CapabilityDispatcher.deserializeNBT(CapabilityDispatcher.java:127) ~[forge-1.20.1-47.2.20-universal.jar%23470!/:?] {re:classloading}
12152 | at net.minecraftforge.common.capabilities.CapabilityDispatcher.deserializeNBT(CapabilityDispatcher.java:35) ~[forge-1.20.1-47.2.20-universal.jar%23470!/:?] {re:classloading}
12153 | at net.minecraftforge.common.util.LevelCapabilityData.read(LevelCapabilityData.java:35) ~[forge-1.20.1-47.2.20-universal.jar%23470!/:?] {re:classloading}
12154 | at net.minecraftforge.common.util.LevelCapabilityData.load(LevelCapabilityData.java:26) ~[forge-1.20.1-47.2.20-universal.jar%23470!/:?] {re:classloading}
12155 | at net.minecraft.server.level.ServerLevel.lambda$initCapabilities$24(ServerLevelMixin.java:1421) ~[server-1.20.1-20230612.114412-srg.jar%23465!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:libx:level_load,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin,pl:mixin:APP:mixins.arclight.core.json:server.level.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:majruszlibrary-common.mixins.json:IMixinServerLevel,pl:mixin:APP:majruszlibrary-common.mixins.json:MixinServerLevel,pl:mixin:APP:pehkui.mixins.json:compat117plus.ServerWorldMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:apugli.mixins.json:common.ServerWorldMixin,pl:mixin:APP:yawp.mixins.json:ServerWorldMixin,pl:mixin:APP:immersive_melodies.mixin.json:ServerWorldMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:activationrange.ServerWorldMixin_ActivationRange,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A,re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load}
12156 | at net.minecraft.world.level.storage.DimensionDataStorage.m_164868_(DimensionDataStorage.java:70) ~[server-1.20.1-20230612.114412-srg.jar%23465!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
12157 | at net.minecraft.world.level.storage.DimensionDataStorage.m_164858_(DimensionDataStorage.java:54) ~[server-1.20.1-20230612.114412-srg.jar%23465!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
12158 | at net.minecraft.world.level.storage.DimensionDataStorage.m_164861_(DimensionDataStorage.java:39) ~[server-1.20.1-20230612.114412-srg.jar%23465!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
12159 | at net.minecraft.server.level.ServerLevel.initCapabilities(ServerLevelMixin.java:1421) ~[server-1.20.1-20230612.114412-srg.jar%23465!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:libx:level_load,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin,pl:mixin:APP:mixins.arclight.core.json:server.level.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:majruszlibrary-common.mixins.json:IMixinServerLevel,pl:mixin:APP:majruszlibrary-common.mixins.json:MixinServerLevel,pl:mixin:APP:pehkui.mixins.json:compat117plus.ServerWorldMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:apugli.mixins.json:common.ServerWorldMixin,pl:mixin:APP:yawp.mixins.json:ServerWorldMixin,pl:mixin:APP:immersive_melodies.mixin.json:ServerWorldMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:activationrange.ServerWorldMixin_ActivationRange,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A,re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load}
12160 | at net.minecraft.server.level.ServerLevel.<init>(ServerLevelMixin.java:244) ~[server-1.20.1-20230612.114412-srg.jar%23465!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:libx:level_load,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin,pl:mixin:APP:mixins.arclight.core.json:server.level.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:majruszlibrary-common.mixins.json:IMixinServerLevel,pl:mixin:APP:majruszlibrary-common.mixins.json:MixinServerLevel,pl:mixin:APP:pehkui.mixins.json:compat117plus.ServerWorldMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:apugli.mixins.json:common.ServerWorldMixin,pl:mixin:APP:yawp.mixins.json:ServerWorldMixin,pl:mixin:APP:immersive_melodies.mixin.json:ServerWorldMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:activationrange.ServerWorldMixin_ActivationRange,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A,re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load}
12161 | at whocraft.tardis_refined.common.dimension.forge.DimensionHandlerImpl.createDimension(DimensionHandlerImpl.java:69) ~[tardis_refined-1.20.1-2.0.3.jar%23438!/:?] {re:classloading}
12162 | at whocraft.tardis_refined.common.dimension.DimensionHandler.createDimension(DimensionHandler.java) ~[tardis_refined-1.20.1-2.0.3.jar%23438!/:?] {re:classloading}
12163 | at whocraft.tardis_refined.common.dimension.DimensionHandler.getOrCreateInterior(DimensionHandler.java:95) ~[tardis_refined-1.20.1-2.0.3.jar%23438!/:?] {re:classloading}
12164 | at whocraft.tardis_refined.common.dimension.DimensionHandler.loadLevels(DimensionHandler.java:113) ~[tardis_refined-1.20.1-2.0.3.jar%23438!/:?] {re:classloading}
12165 | at whocraft.tardis_refined.forge.CommonBus.onServerStart(CommonBus.java:43) ~[tardis_refined-1.20.1-2.0.3.jar%23438!/:?] {re:classloading}
12166 | at whocraft.tardis_refined.forge.__CommonBus_onServerStart_ServerStartedEvent.invoke(.dynamic) ~[tardis_refined-1.20.1-2.0.3.jar%23438!/:?] {re:classloading,pl:eventbus:B}
12167 | at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2386!/:?] {}
12168 | at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2386!/:?] {}
12169 | at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2386!/:?] {}
12170 | at net.minecraftforge.server.ServerLifecycleHooks.handleServerStarted(ServerLifecycleHooks.java:115) ~[forge-1.20.1-47.2.20-universal.jar%23470!/:?] {re:mixin,re:classloading}
12171 | at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2032) ~[server-1.20.1-20230612.114412-srg.jar%23465!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:otyacraftengine-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:majruszlibrary-common.mixins.json:MixinMinecraftServer,pl:mixin:APP:tardis_refined-common.mixins.json:MinecraftServerStorageAccessor,pl:mixin:APP:craftedcore.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
12172 | at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23465!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:otyacraftengine-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:majruszlibrary-common.mixins.json:MixinMinecraftServer,pl:mixin:APP:tardis_refined-common.mixins.json:MinecraftServerStorageAccessor,pl:mixin:APP:craftedcore.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
12173 | at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin}


</body>
</html>

**Comment by Jeryn99** [comment]
craftbukkit?

**Comment by ZeroDragoneer** [comment]
i am using arclight which is forge + bukkit/spigot

**Comment by Jeryn99** [comment]
We do not support that

**Comment by ZeroDragoneer** [comment]
oh that why.

**Comment by Jeryn99** [comment]
Hello,

Thank you for reaching out! Unfortunately, we do not provide support for issues related to hybrid server platforms like Arclight or Magma.

Our support is limited to the following platforms:
- **Forge**
- **Fabric**
- **NeoForge**

If you're encountering issues on a supported platform, please feel free to provide more details, and we'll do our best to assist you.

Thanks for your understanding!

**Comment by bellibear** [comment]
I have this same issue but im just using forge
