### ISSUE TITLE
Multiblocks break and don't work with mods that dynamically change minecraft's blocks

### ISSUE THREAD

**Issue by ArcaneCyanide** [CommandrMoose/TardisRefined#361]
### Issue description

For example diagonal windows automatically changes default minecraft windows to the special modded version when placed. assumedly because it's a different id and not the exact specific id for minecraft window panes, it breaks the multistructure, not being recognized as a valid block and therefore leaving the multistructure incomplete. 

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

Forge version 47.3.0

### Tardis Refined version

v2.0.6

**Comment by 50ap5ud5** [comment]
Are you using the Diagonal Walls mod? 

If so, this is a known issue caused by the Diagonal Walls Mod directly replaces the Minecraft wall blocks which we cannot detect. We may be able to resolve it in future releases. For now, you will need to remove the Diagonal Walls Mod, sorry.

See the linked issue for more information.
https://github.com/Fuzss/diagonalwalls/issues/8.

**Comment by ArcaneCyanide** [comment]
Yes diagonal walls and diagonal windows. Thank you, it sucks but it is what
it is, hopefully someday a fix can be found and implemented. Awesome mod by
the way.
